for c=1:C1,

  uicontrol('Style','Pushbutton','String',colours(c,:),...
            'Callback',['colormap(',colours(c,:) '(64))'],...
            'Position',[left top-c*dh dw 0.9*dh],'Units','Normalized');

end;

hinterp = ['h = get(gcf,''Children'');',...
		   'h1 = get(h(',int2str(C1+4),'),''Children'');',...
		   'set(h1,''EdgeColor'',''none'',''FaceColor'',''interp'');',...
		   'h2 = get(h(',int2str(C1+5),'),''Children'');',...
		   'set(h2,''EdgeColor'',''none'',''FaceColor'',''interp'');'];
		   
